### PR TITLE
Add a feed to retrieve the rss feed for past/former sponsors

### PR DESCRIPTION
**Pull request by rduivenvoorde**
@timlinux @ann26 is this ok? To retrieve the past sponsors?

### CODE REVIEW

**Comment by timlinux** [comment]
Thanks for this @rduivenvoorde  - what about a link in the gui? Happy without it?

**Comment by timlinux** [comment]
@ann26 can you add the past sponsors button and also a test so that our coverage is not reduced? Please make it a meaningful test that inserts some current and expired sponsors and tests we get back the correct set from each feed. Than merge.

**Comment by rduivenvoorde** [comment]
@timlinux I'm ok without a button. I think I'm the only one to use it anyway  :-)

**Comment by rduivenvoorde** [comment]
@ann26 if you give me some examples/pointers I'm happy to add some tests too.

**Comment by ann26** [comment]
Hi @timlinux and @rduivenvoorde I added the button and tests in #940

**Pull request merged**
