### PR TITLE
add rejection status and page

### LINKED ISSUE #980: Certifying organization status
There needs to be a way to indicate which pending organizations have been contacted. Then those of us who are making initial contact can mark those applications as pending.

### PR DESCRIPTION
**Pull request by ann26**
fix #980 

This PR:
- added rejected (Boolean) on certifying organisation model, default is False
- Staff and managers can reject pending certifying organisation
- added rejected organisation

Peek 2019-08-04 22-33

When a certifying organisation is rejected, an email will be sent to its owner as shown below:
```
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Subject: Projecta - Your organisation is not approved
From: tim@kartoza.com
To: hi@bnhr.xyz
Date: Sun, 04 Aug 2019 15:35:56 -0000
Message-ID: <20190804153556.2084.61255@uwsgi>

Dear Ben Hur Pintor,

We are sorry that your certifying organisation has not been approved. 
The following is the details of your organisation:

Name of organisation: BNHR
Project: QGIS
Status: Rejected, because we need more info

For further information please visit: http://0.0.0.0:61202/en/qgis/about/

Sincerely,
Tim Sutton
```

in admin, I added filter for country, approved and rejected:
Peek 2019-08-04 22-55 2

### CODE REVIEW

**Comment by ann26** [comment]
hi @timlinux what do you think?

**Comment by timlinux** [comment]
Looking great @ann26.

@kurtmenke what do you think?

@ann26 i think we should have a new menu item in certifications so you can go to

Approved 
Pending 
Rejected 

And have each filtered accordingly so that you don't need to look at all of them always. Cool to have the admin ui stuff but our users don't generally go to admin (even cert managers).

**Comment by ann26** [comment]
hi @timlinux how about this?
Peek 2019-08-06 11-40

**Comment by geomenke** [comment]
+1 to these changes. I submitted a request related to this last October.
Allowing people managing the certification system to enter a date when the
contact person was contacted.
https://github.com/kartoza/prj.app/issues/980

This would really help manage the system. Currently I know I've contacted
many and often they just don't respond back or need months to prepare their
materials.

BTW it has been a long time since I received a notification about a new
org. If that can be addressed it would really help expedite the process and
keep the pending list down.
Kurt

**************************

Kurt Menke
Bird’s Eye View
QGIS Certified Trainer
3016 Santa Clara Ave SE
Albuquerque, NM 87106

www.BirdsEyeViewGIS.com <http://www.birdseyeviewgis.com/>

Cell: 505-362-1776
Work: 505-265-0243
Fax: 505-265-0243

QCooperative
https://www.qcooperative.net/

Blogger @Community Health Maps
https://communityhealthmaps.nlm.nih.gov/

Author:
Discover QGIS 3.x
*https://locatepress.com/dq3 <https://locatepress.com/dq3> *

Mastering Geospatial Development with QGIS 3.x
https://www.packtpub.com/application-development/mastering-geospatial-development-qgis-3x-third-edition

**Comment by ann26** [comment]
hi @geomenke how about this? You can update the status of the pending certifying organisation:
Peek 2019-08-28 10-06

**Comment by timlinux** [comment]
That looks great @ann26 - Are the states coming from a predefined list?

If not can you make it that there is a model for certification review states that we can manage in admin. Can. you merge and deploy on staging so we can play with it?

**Comment by ann26** [comment]
hi @timlinux no, it's a free text, you can add any text for the status.
Ok I will deploy this to staging, and let me know what you think after you play with it.

**Pull request merged**
