### PR TITLE
Fix 979 - Add ability to describe certification programme

### PR DESCRIPTION
**Pull request by timlinux**
@ann26 Its a bit ugly - would appreciate any beautifcation suggestions :-)

hr

### CODE REVIEW

**Comment by ann26** [comment]
hi @timlinux how about displaying it as a pop up?

**Comment by timlinux** [comment]
@ann26 could you tweak my work to add a popup and make the tests pass? I have no idea why they are failing :-(

**Comment by ann26** [comment]
hi @timlinux will do

**Comment by ann26** [comment]
hi @timlinux I made a PR here: https://github.com/timlinux/projecta/pull/4

**Pull request closed without merging**
